Refactor calendarium to TS
cesium/calendarium pull request #27
Opened 2022-09-11 19:49 UTC by MarioRodrigues10

2022-09-12 08:57 UTC, ruioliveira02 approved these changes

2022-09-12 09:01 UTC, ruioliveira02 requested changes
You changed the logo file but forgot to change it in the footer. Please fix it

2022-09-13 18:22 UTC, EnzoVieira requested changes
Add typing to useTheme context

2022-09-13 18:22 UTC, EnzoVieira commented on components/Theme/Theme.tsx
> +const ThemeContext = createContext(null);
Add a typing for the context

<img width="458" alt="Captura de Tela 2022-09-13 às 19 10 17" src="https://user-images.githubusercontent.com/73349819/189978225-5329084c-683c-4702-9004-c49c49905d65.png">

And some small typing changes

<img width="457" alt="Captura de Tela 2022-09-13 às 19 11 22" src="https://user-images.githubusercontent.com/73349819/189979207-83598011-1f37-4b24-80c7-53d9644fffd3.png">

this way vscode will give autocomplete when using useTheme() hook

<img width="514" alt="Captura de Tela 2022-09-13 às 19 20 36" src="https://user-images.githubusercontent.com/73349819/189980227-079bef25-38ae-4e51-afca-e8471a0a9f54.png">

2022-09-14 00:35 UTC, EnzoVieira approved these changes

2022-09-14 12:57 UTC, merged