Month Selection Component Change
cesium/calendarium pull request #8
Opened 2022-02-14 23:55 UTC by pedrops164

Changed the Month Selection Component to receive functions onMonthChange and onYearChange as properties. Also added next and previous month buttons, and a text indicanting the current month.
I didn't understand how I could represent the month/year as properties, since I don't know how I would change the value of those properties once the user clicked the next or previous buttons.

2022-02-15 17:55 UTC, ruioliveira02 requested changes

2022-02-15 17:55 UTC, ruioliveira02 commented on components/MonthSelection.js
> +import { useState } from 'react'
```suggestion

```
Remove this as it won't be needed

2022-02-15 17:55 UTC, ruioliveira02 commented on components/MonthSelection.js
> +    const [year, setYear] = useState(2020)
```suggestion
```

Component should be stateless

2022-02-15 17:55 UTC, ruioliveira02 commented on components/MonthSelection.js
> +        }
```suggestion
        const names = ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho",
         "Julho",   "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"];
         
         return names[month];
        
```

This is a lot cleaner

2022-02-15 17:55 UTC, ruioliveira02 commented on components/MonthSelection.js
> +const MonthSelection = ({onMonthChange, onYearChange}) => {
```suggestion
const MonthSelection = ({onMonthChange, onYearChange, month, year}) => {
```

The year and month should be received as properties

2022-02-15 17:55 UTC, ruioliveira02 commented on components/MonthSelection.js
> +        else setMonth(month + 1)
```suggestion
        else 
           onMonthChange (month + 1);
```

2022-02-15 17:55 UTC, ruioliveira02 commented on components/MonthSelection.js
> +            onYearChange //calls function onYearChange??
```suggestion
            onMonthChange(0);
            onYearChange(year + 1);
```

Functions passed as arguments still have to be called using parenthesis. This also applies for the previousMonth function.

2022-02-15 17:55 UTC, ruioliveira02 commented on components/MonthSelection.js
> +        onMonthChange //calls function onMonthChange??
```suggestion
```

2022-02-15 17:55 UTC, ruioliveira02 commented on components/MonthSelection.js
> +        <text>{showMonth()}</text>
```suggestion
        <h2>{showMonth()}</h2>
```

Text tags are not a thing.

2022-02-15 19:22 UTC, pedrops164 reviewed
In order to change the months with the scroll wheel, while maintaining the component stateless, should the component receive the scroll wheel Y and the function to change this value?

2022-02-19 20:23 UTC, ruioliveira02 commented
> In order to change the months with the scroll wheel, while maintaining the component stateless, should the component receive the scroll wheel Y and the function to change this value?

Let's not do that now.

2022-02-20 21:08 UTC, ruioliveira02 requested changes
Please move the file ```components/MonthSelection.js``` to ````components/MonthSelection/index.jsx````

In regards to styling, look for similar to [SEI](https://seium.org). But for now let's wait for other components to be developed to create a uniform design

2022-09-06 12:46 UTC, ruioliveira02 commented
Same reason as #7. Thank you for your contribution regardless :pray:

2022-09-06 12:46 UTC, closed without merging